### ISSUE TITLE
[wifi-login-pages] Set page title

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#155]
For each page of the app we should have a title, eg: `{page_title} - {organization_name}`.

We should have a `title` attribute in the org-config of each component, translatable, eg:
```yaml
registration_form:
    title:
        en: "Sign up"
```

We should add a test for each component to ensure the tile is changed as expected.

Also the main title should be allowed to be multilingual, now we have:

```yaml
client:
  # <title> value
  title: "WiFi Login"
```

we shall switch to:
```yaml
client:
  # <title> value
  title:
    en: "WiFi Login"
    it: "Accesso WiFi"
    # other languages...
```
