### ISSUE TITLE
[bug] Variants: lists should overwrite parent

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#424]
**How to replicate the issue:**

Given an organization having a conf like:

```yaml
---
name: "Org"
client:
  components:
    contact_page:
      social_links:
        - url: "http://org.com/"
          text:
            en: "Org"
```

and a variant version like:

```
---
name: "Variant"
client:
  components:
    contact_page:
      social_links:
        - url: "http://url.com/"
          text:
            en: "Variant"
```

**Expected result**: `social_links` contains only a link to `url.com`.

**Actual result**: both links (parent org link and variant) are shown.

**General recommendations**: We had similar issues in netjsonconfig and OpenWISP controller, generally when users write different lists they want these to be overridden completely in 99% cases. I fixed that problem in OpenWISP controller and netjsonconfig, we should do the same here and add a brief mention in the variants README section. When lists are being merged, the variant shall overwrite completely the previous list.
