### ISSUE TITLE
[wifi-login-pages] Avoid the need of repeating URLs for each organization

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#59]
These URLs should no be repeated for each organization:
```
server:
  host: "http://localhost:8000"
  proxy_urls:
    password_change: "/api/v1/{org_slug}/account/password/change"
    password_reset: "/api/v1/{org_slug}/account/password/reset"
    password_reset_confirm: "/api/v1/{org_slug}/account/password/reset/confirm"
    registration: "/api/v1/{org_slug}/account"
    user_auth_token: "/api/v1/{org_slug}/account/token"
    validate_auth_token: "/api/v1/{org_slug}/account/token/validate"
    authorize: "/api/v1/authorize"
```

The should be stored elsewhere in the code, not in the YAML configuration of each organization.

**Comment by Vivekrajput20** [comment]
@nemesisdesign repeating the urls is not required even now. If proxy_urls is not present in the org config, default organization's urls are used. Even if just one url is provided like 
```
proxy_urls:
    validate_auth_token: "/api/v1/new_url/{org_slug}/account/token/validate"
```
this leads to generation of a config which has all the other urls as default organization's url and only this one updated. Like:
```
  proxy_urls:
    password_change: "/api/v1/{org_slug}/account/password/change"
    password_reset: "/api/v1/{org_slug}/account/password/reset"
    password_reset_confirm: "/api/v1/{org_slug}/account/password/reset/confirm"
    registration: "/api/v1/{org_slug}/account"
    user_auth_token: "/api/v1/{org_slug}/account/token"
    validate_auth_token: "/api/v1/new_url/{org_slug}/account/token/validate"
    authorize: "/api/v1/authorize"
```
