### ISSUE TITLE
[menu] Allow specifying if links should be shown to authenticated or unauthenticated users

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#93]
We should be able to specify whether links should be shown to any user, only authenticated users or unauthenticated users, eg:

```
links:
  - text:
      en: "Sign In" #link text in english
    url: "/<slug>/login"
    authenticated: false
  - text:
      en: "Sign Up"
    url: "/<slug>/registration"
    authenticated: false
  - text:
      en: "Change password"
    url: "/<slug>/change-password"
    authenticated: true
  - text:
      en: "About this service"
    url: "https://somewebsite.com/about"
```

In the example above, the first two links must be shown only to users who are not authenticated, the third link should be shown only to users which are authenticated and the last one to any user (current behavior).
